# Generated by Django 3.1.7 on 2022-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='design_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='drawn_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
