# Generated by Django 3.1.7 on 2022-01-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220123_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_by',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='drawn_by',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.TextField(),
        ),
    ]
