# Generated by Django 3.1.7 on 2022-01-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220123_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='persfective1',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='persfective2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='persfective3',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='persfective4',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
