# Generated by Django 3.1.7 on 2022-02-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
